"""Initial Schema

Revision ID: 92e43855c299
Revises: 
Create Date: 2026-02-05 16:02:02.616575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '92e43855c299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('questions',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('resumes',
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('skills_text', sa.Text(), nullable=True),
    sa.Column('experience_text', sa.Text(), nullable=True),
    sa.Column('certifications_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('user_info',
    sa.Column('info_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('info_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('interviews',
    sa.Column('interview_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('resume_id', sa.BigInteger(), nullable=True),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_questions_planned', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('interview_id')
    )
    op.create_table('interview_evaluations',
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decision_reason_text', sa.Text(), nullable=True),
    sa.Column('decision_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('evaluation_scores',
    sa.Column('score_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.Column('score_value', sa.Float(), nullable=True),
    sa.Column('rationale_text', sa.Text(), nullable=True),
    sa.Column('evidence_message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['interview_evaluations.evaluation_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('whiteboard_notes',
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whiteboard_notes')
    op.drop_table('evaluation_scores')
    op.drop_table('messages')
    op.drop_table('interview_evaluations')
    op.drop_table('interviews')
    op.drop_table('user_info')
    op.drop_table('resumes')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
